title: "EcoSamana Adventures"
description: "Family-friendly eco tours & pirate treasure hunts in Santa Bárbara de Samaná."
baseurl: ""
url: "https://eco-samana.com"

# Optional: keep or remove minima if unused
theme: minima

markdown: kramdown
permalink: /:categories/:title/

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

sass:
  style: compressed

email: eco-samanadventures@gmail.com

social:
  twitter: "https://twitter.com/Fiestaecosafari"
  facebook: "https://facebook.com/profile.php?id"
  instagram: "https://www.instagram.com/eco.samana/"
  tiktok: "https://www.tiktok.com/@elinacalcano"

collections:
  info:
    output: true
    permalink: /info/:name/
